### ISSUE TITLE
Support `scheduler-port` and `worker-port` command line args?

### ISSUE THREAD

**Issue by shwina** [dask/dask-mpi#26]
Would this be as simple as modifying the code around https://github.com/dask/distributed/blob/master/distributed/cli/dask_mpi.py#L63 and https://github.com/dask/distributed/blob/master/distributed/cli/dask_mpi.py#L79?

**Comment by kmpaul** [comment]
Essentially  ...except for the fact that these lines should be in `dask/dask_mpi` and not `dask/distributed`.

The second argument (currently `None`) in both of these calls to `uri_from_host_port` indicates the port selected and the third argument is the default port.  

Would you be motivated enough to put together a PR to `dask/dask_mpi` to do this?

**Comment by shwina** [comment]
Thanks! Yes, I'm happy to

**Comment by mahendrapaipuri** [comment]
I know it is a closed issue, but I notice that the scheduler is not being created at the port number I specify on the CLI. For instance, when I invoke the `dask-mpi` using following command:

`mpirun -np 8 --map-by node dask-mpi --no-nanny --nthreads=1 --memory-limit='100GB' --scheduler-file=scheduler_file.json --interface=ib0 --scheduler-port=8786 &`

these are the first few lines of the dask log:

```
distributed.http.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:    tcp://10.3.0.147:45659
distributed.scheduler - INFO -   dashboard at:           10.3.0.147:8787
distributed.worker - INFO -       Start worker at:     tcp://10.3.0.147:44163
distributed.worker - INFO -          Listening to:     tcp://10.3.0.147:44163
distributed.worker - INFO -       Start worker at:     tcp://10.3.0.147:38812
distributed.worker - INFO -          Listening to:     tcp://10.3.0.147:38812
distributed.worker - INFO -          dashboard at:           10.3.0.147:38046
distributed.worker - INFO - Waiting to connect to:     tcp://10.3.0.147:45659
distributed.worker - INFO -          dashboard at:           10.3.0.147:45534
distributed.worker - INFO - Waiting to connect to:     tcp://10.3.0.147:45659
distributed.worker - INFO - -------------------------------------------------
```
As we can see the dask scheduler is created at port 45659 rather than 8786. Looking at the source code https://github.com/dask/dask-mpi/blob/b1638a44511bd701fa31698a90196926f5e8f89a/dask_mpi/cli.py#L99-L104, I see that scheduler port is not being passed to `Scheduler` call. Is it normal behaviour? I am newbie to dask, so please excuse me if it is a trivial question.
