### ISSUE TITLE
Verify that Read the Docs is building after master -> main 

### ISSUE THREAD

**Issue by jsignell** [dask/dask-mpi#66]
Spotted on https://github.com/dask/dask-cloudprovider/issues/244#issuecomment-795310925. Read The Docs was still building `latest` from the `master` branch and builds were failing. It was configured to build from the default branch, but had cached the value `master` somewhere. Manually pointing it to  `main` in the RtD control panel fixed things.

**Comment by andersy005** [comment]
@jsignell, thanks for tracking this down. I changed the settings in the RTD control panel. However, the webhook doesn't seem to be working. When I try re-syncing the webhook, I get permissions errors because I don't have admin privileges on this repository: 

![Screen Shot 2021-03-10 at 11 50 51 AM](https://user-images.githubusercontent.com/13301940/110681637-430e7d80-8197-11eb-9ce5-bd5bd7ab8351.png)


I just added you as a maintainer on the RTD project. Could you try re-syncing the webhook when you get a moment?

**Comment by jsignell** [comment]
I think it's all good now. The revision of the docs matches the latest commit on main. Thanks for the ping @andersy005!
